-- =============================================================
-- Contact Tracing Application – Initial SQL Setup
-- Department of Computer Engineering, USC
-- MySQL / phpMyAdmin
-- =============================================================

-- Create and select the database
CREATE DATABASE IF NOT EXISTS cpe_contact_tracing
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE cpe_contact_tracing;

-- -------------------------------------------------------------
-- Table: users
-- Stores all registered individuals (students, faculty, guests)
-- user_id is a surrogate PK; usc_id_number is nullable so that
-- guests/visitors without a USC ID can still be registered.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    user_id         INT             NOT NULL AUTO_INCREMENT,
    usc_id_number   VARCHAR(20)     NULL,           -- NULL for non-USC visitors
    user_type       ENUM(
                        'student',
                        'faculty',
                        'staff',
                        'guest'
                    )               NOT NULL,
    first_name      VARCHAR(50)     NOT NULL,
    middle_name     VARCHAR(50)     NULL,
    last_name       VARCHAR(50)     NOT NULL,
    barangay        VARCHAR(100)    NOT NULL,
    city            VARCHAR(100)    NOT NULL,
    province        VARCHAR(100)    NOT NULL,
    contact_number  VARCHAR(20)     NOT NULL,
    email           VARCHAR(100)    NOT NULL,
    date_registered DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (user_id),
    UNIQUE KEY uq_usc_id (usc_id_number)   -- ensures no duplicate USC IDs
) ENGINE=InnoDB;

-- -------------------------------------------------------------
-- Table: visit_logs
-- One row per entry event; time_out is filled on sign-out.
-- status reflects the current state of that visit row.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS visit_logs (
    visit_id    INT                     NOT NULL AUTO_INCREMENT,
    user_id     INT                     NOT NULL,
    time_in     DATETIME                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    time_out    DATETIME                NULL,       -- NULL until the user signs out
    status      ENUM('IN', 'OUT')       NOT NULL DEFAULT 'IN',

    PRIMARY KEY (visit_id),
    CONSTRAINT fk_visit_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=InnoDB;

-- -------------------------------------------------------------
-- Table: admins
-- Standalone table – no FK link to users.
-- Password must be stored as a bcrypt / Argon2 hash in the app
-- layer before inserting; the VARCHAR(255) accommodates that.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admins (
    admin_id    INT             NOT NULL AUTO_INCREMENT,
    usc_id_number   VARCHAR(20)     NULL,           -- NULL for non-USC visitors
    username    VARCHAR(50)     NOT NULL,
    password    VARCHAR(255)    NOT NULL,   -- store HASHED value only

    PRIMARY KEY (admin_id),
    UNIQUE KEY uq_admin_username (username)
) ENGINE=InnoDB;

-- -------------------------------------------------------------
-- Seed: default admin account
-- Replace the password value below with an actual bcrypt hash
-- generated by your application before going live.
-- Plaintext placeholder: Admin@CpE2025
-- -------------------------------------------------------------
INSERT INTO admins (username, password)
VALUES (
    '6769420',
    'cpe_admin@usc.edu.ph',
    'cpe_admin_12345'
);

-- -------------------------------------------------------------
-- Indexes for the admin search features
-- Covers: city, barangay, province, usc_id_number,
--         last_name / first_name, and time_in range queries
-- -------------------------------------------------------------
CREATE INDEX idx_users_city         ON users (city);
CREATE INDEX idx_users_barangay     ON users (barangay);
CREATE INDEX idx_users_province     ON users (province);
CREATE INDEX idx_users_usc_id       ON users (usc_id_number);
CREATE INDEX idx_users_last_name    ON users (last_name);
CREATE INDEX idx_users_first_name   ON users (first_name);
CREATE INDEX idx_visit_logs_time_in ON visit_logs (time_in);

-- =============================================================
-- End of setup script
-- =============================================================